name: API Tests

on:
    push:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Build binary
              run: cargo build --release

            - name: Push
              run: |
                  git fetch origin build-binary
                  git checkout build-binary
                  git add --a; git commit -m "Update binary"; git push origin build-binary
