name: Create Release

on:
    push:
        # Sequence of patterns matched against refs/tags
        tags:
            - "test-v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
    build:
        name: Create Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Build Rust release
              run: |
                    cargo build --release

            - name: Create Release
              id: create_release
              uses: softprops/action-gh-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }} # This token is provided by Actions, you do not need to create your own token
              with:
                  tag_name: ${{ github.ref_name}}
                  name: Release ${{ github.ref_name }}
                  body: "Rust binary built for Linux x86_64"
                  files: target/release/charms
                  draft: false
                  prerelease: false
