name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release
    - name: GitHub Upload Release Artifacts
      uses: Roang-zero1/github-upload-release-artifacts-action@v3.0.0
      with:
          name: charms-binary
          path: target/release/charms
          retention-days: 300
